# Generated by cucumber-sinatra. (Fri Feb 10 18:51:27 +1000 2012)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Teaser::App

class Teaser::AppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  Teaser::AppWorld.new
end
